ZSH_THEME="half-life" # set by `omz`

export DEBUG_CONFIG_FLAG=false

if $DEBUG_CONFIG_FLAG
then 
  echo "Loading config in debug mode."
  zmodload zsh/zprof
fi
source $HOME/.zsh/exports.zsh # You want this first since it has a lot of exports.
source $ZSH_DIR/aliases.zsh
source $ZSH_DIR/fzf-settings.zsh
source $ZSH_DIR/setup.zsh

plugins=(git brew conda-zsh-completion vi-mode)

# enables vim keybindings
bindkey -v


# Initialize oh-my-zsh. Everything above this line needs to happen before oh-my-zsh is loaded! Weird!
source $ZSH/oh-my-zsh.sh

if $DEBUG_CONFIG_FLAG
then 
  zprof
fi